<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types=1);

namespace MagedIn\ViewProductPage\Block\Adminhtml\Catalog\Product\Edit;

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Catalog\Block\Adminhtml\Product\Edit\Button\Generic;
use Magento\Catalog\Model\Product;
use Magento\Catalog\Model\Product\Url as ProductUrl;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\UiComponent\Context;
use Magento\Store\Model\StoreManagerInterface;

class ViewProduct extends Generic
{
    /**
     * @var ProductUrl
     */
    private ProductUrl $productUrl;

    /**
     * @var StoreManagerInterface
     */
    private StoreManagerInterface $storeManager;

    /**
     * @var RequestInterface
     */
    private RequestInterface $request;

    /**
     * @param Context $context
     * @param Registry $registry
     * @param ProductUrl $productUrl
     * @param StoreManagerInterface $storeManager
     * @param RequestInterface $request
     */
    public function __construct(
        Context $context,
        Registry $registry,
        ProductUrl $productUrl,
        StoreManagerInterface $storeManager,
        RequestInterface $request
    ) {
        parent::__construct($context, $registry);
        $this->productUrl = $productUrl;
        $this->storeManager = $storeManager;
        $this->request = $request;
    }

    /**
     * Get Button Data
     *
     * @return array
     */
    public function getButtonData(): array
    {
        return [
            'label' => __('View on Storefront'),
            'on_click' => sprintf("window.open('%s');", $this->getProductUrl()),
            'class' => 'secondary',
            'sort_order' => 1,
        ];
    }

    /**
     * @return string
     */
    public function getProductUrl(): string
    {
        /** @var Product | ProductInterface $product */
        $product = $this->getProduct();
        $product->setStoreId($this->getResolvedStoreId());
        return $this->productUrl->getProductUrl($product);
    }

    /**
     * DocBlock for method.
     *
     * @return int
     */
    private function getResolvedStoreId(): int
    {
        try {
            /**
             * Confirm the store ID provided really exists.
             * @var int $storeId
             */
            $defaultStoreId = (int) $this->storeManager->getDefaultStoreView()->getId();
            $storeId = $this->request->getParam('store', $defaultStoreId);
            $storeId = $this->storeManager->getStore($storeId)->getId();
        } catch (NoSuchEntityException $e) {
            $storeId = $this->storeManager->getDefaultStoreView()->getId();
        }
        return (int) $storeId;
    }
}
